### ISSUE TITLE
Fix Repo Logos

### ISSUE THREAD

**Issue by chamathpali** [RGU-Computing/unimate#6]
There are two missing logo or incorrect paths

**Comment by chamathpali** [comment]
@VihangaAW

**Comment by VihangaAW** [comment]
This issue has been fixed in #7

**Comment by chamathpali** [comment]
@VihangaAW please use this for GCRF. - https://mrc.ukri.org/mrc/assets/Image/logos/gcrf_full%20colour-v2.jpg

And this for RGU -  the atteached
![RGU-Riverside-Logo-PURPLE-AW](https://user-images.githubusercontent.com/5123109/136659675-629aca9c-4034-4437-b799-5065504e4b25.png)
.

**Comment by VihangaAW** [comment]
This issue has been fixed in #8
